# Generated by Django 4.0.5 on 2022-06-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('genre', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('directed_by', models.CharField(max_length=120)),
                ('release_date', models.DateField()),
                ('synopsis', models.TextField()),
            ],
        ),
    ]
